title: "Umar Sheikh"
author: "Umar"
description: "My Experience"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout
show_excerpts: true
show_frame: true
show_sidebar: false
show_minimal: false

# Menu
navigation:
  - {file: "archive.html", sidebaricon: home}
  - {file: "README.md", sidebaricon: address-card}

external:
  - {title: Mail, icon: envelope, url: "mailto:author@example.com"}
  - {title: Github, icon: github, url: "https://github.com/niklasbuschmann/contrast"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

plugins:
  - jekyll-feed
