# Site Settings
title: "Umar Sheikh"
author: "Umar"
description: "My Experience"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout
show_excerpts: true
show_frame: true
show_sidebar: false
show_minimal: false

# Navigation Menu
navigation:
  - {file: "archive.html"}          # sidebaricon hata diya
  - {file: "README.md"}             # sidebaricon hata diya
  - {file: "contact.md"}            # Contact page add kiya

# External Links
external:
  - {title: Mail, icon: "✉", url: "mailto:umarshk466742@gmail.com"}
  - {title: GitHub, icon: "⚡", url: "https://github.com/your-github-username"}
  - {title: WhatsApp, icon: "💬", url: "https://wa.me/923125400000"}
  - {title: Subscribe, icon: "📡", url: "/feed.xml"}

# Comments
comments:

# Plugins
plugins:
  - jekyll-feed
